config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'static_pages#home'
    resources :sms_configs
    get 'password_resets/new'
    get 'password_resets/edit'
    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'contact_info' => 'static_pages#contact_info'
    get    'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    get 'contacts/:id/send_sms' => 'contacts#send_sms', :as => 'send_sms_contact'
    post 'contacts/sms_sender' => 'contacts#sms_sender', :as => 'sms_sender_contact'

    get 'contacts/:id/export' => 'contacts#export_vcf', :as => 'export_contacts'
    get 'contacts/import' => 'contacts#import', :as => 'import_contacts'
    get 'contacts/:id/create_email' => 'contacts#create_email', :as => 'create_email_contact'
    post 'contacts/:id/send_email' => 'contacts#send_email', :as => 'send_email_contact'

    resources :contacts
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
end
get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
get '', to: redirect("/#{I18n.default_locale}/")

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: false, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }, :allow_blank => true
  validates :name, presence: false
  validates :phone_number, presence: false
  belongs_to :user
  def self.search(search)
    if search
     self.where("email like ? OR phone_number like ? OR name like ?", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      self.all
    end
  end
end

app/controllers/contacts_controller.rb
require 'google_contacts_api'
require 'vpim/vcard'

class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy, :send_sms, :create_email, :send_email, :export_vcf]
  before_action :logged_in_user

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.paginate(page: params[:page], :per_page =>20).where(:user_id => current_user.id).search(params[:search])
    @sms_config = SmsConfig.find_by_user_id(current_user.id)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, flash: {success: t('contact_successfully_created')} }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_sms
  end

  def sms_sender
    require 'rest-client'
    @contact = Contact.find(params[:id])
    config = SmsConfig.find_by_user_id(current_user.id)
    success = false

    if config and @contact.phone_number
      sms_sender = SmsSender.new(config)
      success = sms_sender.send_sms(@contact.phone_number, params[:message])
    end

    if success
      flash = {
          success: t('message_sent')
      }
    else
      flash = {
          danger: t('sms_not_sent')
      }
    end
    redirect_to contacts_path, flash: flash
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, flash: {success: t('contact_updated') } }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, flash: {success: t('contact_destroyed')} }
      format.json { head :no_content }
    end
  end

  def import
    client = OAuth2::Client.new(CLIENT_ID, CLIENT_SECRET,
                                site: 'https://accounts.google.com',
                                token_url: '/o/oauth2/token',
                                authorize_url: '/o/oauth2/auth')
    if params[:code] != nil
      token = client.auth_code.get_token(params[:code], :redirect_uri => 'https://salty-brook-9086.herokuapp.com/pl/contacts/import')
      google_contacts_user = GoogleContactsApi::User.new(token)
      contacts = google_contacts_user.contacts.to_a.sort_by{|x| x.full_name or t('unknown')}
      contacts.each { |google_contact|
        phone_number = google_contact.phone_numbers.first
        email = google_contact.primary_email
        unless Contact.find_by_email_and_phone_number_and_user_id(email, phone_number, current_user.id)
          contact = Contact.new
          contact.name = google_contact.full_name || t('unknown')
          contact.email = email
          contact.phone_number = phone_number
          contact.user = current_user
          contact.save
        end

      }
      redirect_to contacts_url, flash: { success: t('imported_successfully')}
    else
      puts import_contacts_url
      url = client.auth_code.authorize_url(scope: 'https://www.google.com/m8/feeds',
                                           redirect_uri: 'https://salty-brook-9086.herokuapp.com/pl/contacts/import')
      redirect_to url
    end
  end

  def create_email

  end

  def send_email
    UserMailer.email_to_contact(@contact, current_user.email, params[:subject], params[:message]).deliver_now
    redirect_to contacts_url, flash: { success: t('email_sent') }
  end

  def export_vcf
    card = Vpim::Vcard::Maker.make2 do |maker|

      maker.add_email(@contact.email)
      maker.add_name do |name|
        splitted = @contact.name.split
        name.prefix = ''
        if splitted.size == 1
          name.family = splitted[0]
        end

        if splitted.size == 2
          name.given = splitted[0]
          name.family = splitted[1]
        end
      end

      if @contact.phone_number
        maker.add_tel(@contact.phone_number) { |e| e.location = 'work'}
      end

    end

    send_data card.to_s, :type => 'text/x-vcard', :filename => @contact.name + '.vcf'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone_number, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_email_form.erb
<%= @contact.name %>
<%= @contact.email %>
<%= @contact.phone_number %>
<%= bootstrap_form_tag url: send_email_contact_path do |f| %>
    <%= f.hidden_field(:id, value: @contact.id) %>
    <%= f.text_field :subject , label: t('subject')  %>
    <%= f.text_area(:message, size: '24x6', :required => true, :maxlength => 300) %>
    <%= f.submit  t('submit') %>
<% end %>

app/views/contacts/_form.html.erb
<%= bootstrap_form_for(@contact) do |f| %>
    <%= f.text_field :name, label: t('name') %>
    <%= f.text_field :email %>
    <%= f.text_field :phone_number, label: t('phone_number') %>
    <%= f.submit t('submit') %>
<% end %>

app/views/contacts/_listing.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th><%= t('name') %> </th>
    <th>Email</th>
    <th><%= t('phone_number') %> </th>
    <th><%= t('options') %> </th>
  </tr>
  </thead>

  <tbody>
  <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone_number %></td>
        <td>
            <%= link_to t('show'), contact, :class => 'btn btn-default' %>
            <%= link_to t('edit'), edit_contact_path(contact), :class => 'btn btn-default' %>
            <% if @sms_config and contact.phone_number %>
              <%= link_to t('send_sms'), send_sms_contact_path(contact), :class => 'btn btn-default' %>
            <% end %>
            <% if contact.email %>
              <%= link_to t('send_email'), create_email_contact_path(contact), :class => 'btn btn-default' %>
            <% end %>
            <%= link_to t('export_vcard'), export_contacts_path(contact), :class => 'btn btn-default' %>
            <%= link_to t('destroy'), contact, :class => 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/contacts/_sms_form.html.erb
<%= @contact.name %>
<%= @contact.email %>
<%= @contact.phone_number %>
<%= form_for(:contact, url: sms_sender_contact_path) do |f| %>
    <%= hidden_field_tag(:id, @contact.id) %>
    <%= text_area(:message, "", size: '24x6', :required => true, :maxlength => 300) %>
    <%= f.submit t('submit')%>
<% end %>

app/views/contacts/create_email.html.erb
<h1>Send Email</h1>

<%= render 'email_form' %>

<%= link_to t('show_contact'), @contact, class: 'btn btn-default' %> |
<%= link_to t('back'), contacts_path, class: 'btn btn-default' %>

app/views/contacts/edit.html.erb
<h1><%= t('edit_contact') %> </h1>

<%= render 'form' %>

<%= link_to t('show'), @contact, class: 'btn btn-default' %> |
<%= link_to t('back'), contacts_path, class: 'btn btn-default' %>

app/views/contacts/index.html.erb
<h1><%= t('contacts') %> </h1>
<p><%= link_to t('import_contacts'), import_contacts_path, class: 'btn btn-default' %></p>

<%= form_tag contacts_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag t('search'), :name => nil %>
  </p>
<% end %>
<%= form_tag contacts_path, :method => :get do %>
  <p>
    <%= link_to t('show_all'), contacts_path, class: "btn btn-lg btn-primary" %>
  </p>
<% end %>

<%= will_paginate %>

<%= render 'contacts/listing' %>

<%= will_paginate %>

<br>

<%= link_to t('new_contact'), new_contact_path, class: 'btn btn-default'%>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to t('back'), contacts_path, class: 'btn btn-default' %>

app/views/contacts/send_sms.html.erb
<h1><%= t('send_sms') %></h1>

<%= render 'sms_form' %>

<%= link_to t('show_contact'), @contact, class: 'btn btn-default' %> |
<%= link_to t('back'), contacts_path, class: 'btn btn-default' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact.phone_number %>
</p>

<%= link_to t('edit'), edit_contact_path(@contact), class: 'btn btn-default' %> |
<%= link_to t('back'), contacts_path, class: 'btn btn-default' %>