config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'static_pages#home'
    resources :sms_configs
    get 'password_resets/new'
    get 'password_resets/edit'
    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'contact_info' => 'static_pages#contact_info'
    get    'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    get 'contacts/:id/send_sms' => 'contacts#send_sms', :as => 'send_sms_contact'
    post 'contacts/sms_sender' => 'contacts#sms_sender', :as => 'sms_sender_contact'

    get 'contacts/:id/export' => 'contacts#export_vcf', :as => 'export_contacts'
    get 'contacts/import' => 'contacts#import', :as => 'import_contacts'
    get 'contacts/:id/create_email' => 'contacts#create_email', :as => 'create_email_contact'
    post 'contacts/:id/send_email' => 'contacts#send_email', :as => 'send_email_contact'

    resources :contacts
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
end
get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
get '', to: redirect("/#{I18n.default_locale}/")

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    kkrampa & MarekAG
  </small>
  <nav>
    <ul>
      <li><%= link_to t('about'),   about_path %></li>
      <li><%= link_to t('contact'), contact_info_path %></li>
      <li><a href="https://github.com/kkrampa/asi-egzamin">Github</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "asi-egzamin", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('home'), root_path %></li>
        <li><%= link_to "FAQ", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to t('users'), users_path %></li>
            <li><%= link_to t('contacts'), contacts_path %></li>
            <li><%= link_to t('setup_sms'), new_sms_config_path %></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('profile'), current_user %></li>
              <li><%= link_to t('edit_profile'), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('log_out'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('sign_in'), login_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t('lang') %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to_unless_current "English", locale: "en" %> </li>
            <li><%= link_to_unless_current "Polski", locale: "pl" %> </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>